#%RAML 0.8
---
title: SocialHub Middleware API
version: v1.0
baseUri: http://socialhub/api
documentation:
  - title: Introduction
    content: |
      API for user-authentication, and retriving posts from twitter and instagram.
      
/registerUser:
  post:
    description: Takes the user details as input and registers user in the database. 
    body:
      application/json:
        example: |  
          {
                  "username" : "m7azeem",
                  "password" : hidden,
                  "email" : "m7azeem@gmail.com"
          }
    responses:
      200:
        body:
          application/json:
            example: |
                {
                  "success" : "true",
                  "message" : null
                }
      401:
        body:
          application/json:
            example: |
              {
                "success" : "false",
                "message" : "Email address already in use!"
              }
      402:
        body:
          application/json:
            example: |
              {
                "success" : "false",
                "message" : "Username already in use!"
              }
/loginUser:
  post:
    description: Takes the user's login details as input, and returns success=true if login details are correct   
    body:
      application/json:
        example: |  
          {
                  "username" : "m7azeem",
                  "password" : hidden
          }
    responses:
      200:
        body:
          application/json:
            example: |
                {
                  "success" : "true",
                  "message" : null
                  "token" : "128bitStringBlablabalabaaljadacio"
                }
      400:
        body:
          application/json:
            example: |
              {
                "success" : "false",
                "message" : "Incorrect password entered."
              }   
/testTwiter:
  post:
    description: Takes the user's login details as input, and returns success=true if login details are correct   
    body:
      application/json:
        example: |  
          {
                  "userName" : "m7azeem",
                  "password" : hidden
          }
    responses:
      200:
        body:
          application/json:
            example: |
                {
                  "success" : "true",
                  "message" : null
                }
      400:
        body:
          application/json:
            example: |
              {
                "success" : "false",
                "message" : "Incorrect password entered."
              }