#%RAML 0.8
---
title: SocialHub Middleware API
version: v1.0
baseUri: http://socialhub/api
documentation:
  - title: Introduction
    content: |
      API for user-authentication, and retriving posts from twitter and instagram.
      
/registerUser:
  description : 'Register a user'
  post:
    description: Takes the user details as input and registers user in the database. 
    body:
      application/json:
        example: |  
          {
                  "username" : "m7azeem",
                  "password" : "hidden",
          }
    responses:
      200:
        body:
          application/json:
            example: |
                {
                  "success" : "true",
                  "message" : null
                }
      401:
        body:
          application/json:
            example: |
              {
                "success" : "false",
                "message" : "Email address already in use!"
              }
      402:
        body:
          application/json:
            example: |
              {
                "success" : "false",
                "message" : "Username already in use!"
              }
/loginUser:
  description : 'Login a user'
  post:
    description: Takes the user's login details as input, and returns success=true if login details are correct   
    body:
      application/json:
        example: |  
          {
                  "username" : "m7azeem",
                  "password" : "hidden"
          }
    responses:
      200:
        body:
          application/json:
            example: |
                {
                  "success" : "true",
                  "message" : null
                  "token" : "sNq2OKmGpA18homq4LJQyXyIc41/IIhq/Uii1zp6T6w="
                }
      400:
        body:
          application/json:
            example: |
              {
                "success" : "false",
                "message" : "Incorrect password entered."
              }
/authenticate:
  description: Allows a client to check validty of a token
  post:
    description: Check if a token given username and token
    body:
      application/json:
        example: |
          {
            "username" : "m7azeem",
            "token" : "sNq2OKmGpA18homq4LJQyXyIc41/IIhq/Uii1zp6T6w="
          }
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "success" : "true",
                "message" : "Token valid"
              }
      400:
        body:
          application/json:
            example: |
              {
                "success" : "false",
                "message" : "Token invalid"
              }
/userDetails/{username}:
  description: Get user details or make changes to user details
  get:
    description: Fetchs the settings of a user, where user={username}
    queryParameters:
      token:
        description: "Client authentication token"
        required: true
        type: string
        example: "sNq2OKmGpA18homq4LJQyXyIc41/IIhq/Uii1zp6T6w="
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "success" : "true"
                "data" : {
                  "username" : "m7azeem",
                  "details" : {
                      "description" : "description",
                      "profilePictureUrl" : "http://someurl.jpg",
                      "theme" : "default",
                      "hasTwitterAccess" : false,
                      "hasInstagramAccess" : true
                    }
                }
              }
      400:
        body:
          application/json:
            example: |
              {
                "success" : "false",
                "message" : "Invalid token | user doens't exists"
              }
  put:
    description: Updates the settings of a user, where user={username}
    queryParameters:
      token:
        description: "Client authentication token"
        required: true
        type: string
        example: "sNq2OKmGpA18homq4LJQyXyIc41/IIhq/Uii1zp6T6w="
    body:
      application/json:
        example: |
          {
            "details" : {
              "description" : "description",
              "profilePictureUrl" : "http://somenewurl.jpg",
              "theme" : "pink"
            }
          }
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "success" : "true",
                "message" : "User details were updated successfully"
              }
      400:
        body:
          application/json:
            example: |
              {
                "success" : "false",
                "message" : "Validation failed, etc."
              }
/authorizeTwitter/{username}:
  description: Get twitter username of a {username}
  post:
    description: Get twitter username
    queryParameters:
      token:
        description: "Client authentication token"
        required: true
        type: string
        example: "sNq2OKmGpA18homq4LJQyXyIc41/IIhq/Uii1zp6T6w="
    body:
      application/json:
        example: |
          {
            "twitter_username" : "balrajbains1337"
          }
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "success" : "true",
                "message" : "Twitter successfully connected"
              }
      400:
        body:
          application/json:
            example: |
              {
                "success" : "false",
                "message" : "Twitter connection failed"
              }
/authorizeInstagram/{username}:
  description: Get access token for Instagram account for a given {username}
  post:
    queryParameters:
      token:
        description: "Client authentication token"
        required: true
        type: string
        example: "sNq2OKmGpA18homq4LJQyXyIc41/IIhq/Uii1zp6T6w="
    body:
      application/json:
        example: |
          {
            "instagram_access_token" : "NPcudxy0yU5T3tBzho7iCotZ3cnetKwcTIRlX0iwRl0&"
          }
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "success" : "true",
                "message" : "Token successfully aquired"
              }
      400:
        body:
          application/json:
            example: |
              {
                "success" : "false",
                "message" : "Failure due to something"
              }
/getTwitterFeed/{username}:
  description: Get Twitter feed for a give {username}
  get:
    description: Get Twitter feed for {username}
    queryParameters:
      token:
        description: "Client authentication token"
        required: true
        type: string
        example: "sNq2OKmGpA18homq4LJQyXyIc41/IIhq/Uii1zp6T6w="
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "success" : "true",
                "data" : {
                  "feed" : [
                    {
                        "user": 'exampleUser',
                        "tweet": 'Example tweet 1',
                        "timestamp": '29/11/2019',
                        "type": 'text',
                        "likes": 20
                    }, {
                        "user": 'exampleUser2',
                        "tweet": 'Example tweet 2',
                        "timestamp": '11/11/2011',
                        "type": 'video',
                        "source": 'http://techslides.com/demos/sample-videos/small.mp4',
                        "sourceType": 'video/mp4',
                        "likes": 5
                    }, {
                        "user": 'exampleUser',
                        "tweet": 'Example tweet 1.2',
                        "timestamp": '23/03/2013',
                        "type": 'image',
                        "source": 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Fernando_Alonso_and_Sergio_Perez_2012_Malaysia.jpg/540px-Fernando_Alonso_and_Sergio_Perez_2012_Malaysia.jpg',
                        "likes": 3
                    }
                  ]
                }
              }
      400:
        body:
          application/json:
            example: |
              {
                "success" : "false",
                "message" : "Invalid token, unable to get feed, etc."
              }
/getInstagramFeed/{username}:
  description: Get Twitter feed for a give {username}
  get:
    description: Get Twitter feed for a give {username}
    queryParameters:
      token:
        description: "Client authentication token"
        required: true
        type: string
        example: "sNq2OKmGpA18homq4LJQyXyIc41/IIhq/Uii1zp6T6w="
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "success" : "true",
                "data" : {
                  "feed" : [
                      {
                          "user" : 'exampleUser'
                          "type": 'image',
                          "source": 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Fernando_Alonso_and_Sergio_Perez_2012_Malaysia.jpg/540px-Fernando_Alonso_and_Sergio_Perez_2012_Malaysia.jpg',
                          "timestamp": '29/11/2013',
                          "caption": 'My new car',
                          "likes": 4
                      }, {
                          "user": 'exampleUser'
                          "type": 'image',
                          "source": 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Replica_of_Auburn_Speedster_-_001.jpg/540px-Replica_of_Auburn_Speedster_-_001.jpg',
                          "timestamp": '29/11/2011',
                          "caption": 'My old car',
                          "likes": 5
                      }, {
                          "user": 'exampleUser2'
                          "type": 'image',
                          "source": 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Austin_Six_Saloon_(1932)_GS3184_5902656341.jpg/540px-Austin_Six_Saloon_(1932)_GS3184_5902656341.jpg',
                          "timestamp": '29/11/2012',
                          "caption": 'My new-old car',
                          "likes": 123
                      }
                  ]
                }
              }
      400:
        body:
          application/json:
            example: |
              {
                "success" : "false",
                "message" : "Invalid token, unable to get feed, etc."
              }
/logout:
  description: Logout a user
  post:
    description: Logout a given user after confirming their token
    body:
      application/json:
        example: |
          {
            "username" : "m7azeem",
            "token" : "sNq2OKmGpA18homq4LJQyXyIc41/IIhq/Uii1zp6T6w="
          }
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "success" : "true",
                "message" : "Logout successful"
              }
      400:
        body:
          application/json:
            example: |
              {
                "success" : "false",
                "message" : "Logout failed, please try again"
              }